'''Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” 
Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.'''

import random
random_number = random.randint(1000, 9999)
random_number = str(random_number)


def input_check():
    while True:
        user_number = input("Guess a 4-digit number: ")
        if user_number.isnumeric() and len(user_number) == 4:
            return user_number


def bulls_cows(number_to_guess, user_number):
    cow = 0
    bull = 0

    for i in range(4):
        if number_to_guess[i] == user_number[i]:
            cow += 1
        elif user_number[i] in number_to_guess:
            bull += 1
        else:
            continue

    print(f"Cows = {cow} \nBulls = {bull}")


while True:

    user_number = input_check()

    print(f"Hidden number is {random_number}")

    if random_number==user_number:
        print(f"Finally you've guessed correctly! It is {random_number}")
        break
    else:
        bulls_cows(random_number, user_number)
